Update WM-IT
Added: automatic program update system and the old design has returned.

diff --git a/WM-IT b/WM-IT
--- a/WM-IT
+++ b/WM-IT
@@ -8,20 +8,16 @@ WALLPAPER="WM-IT"
 function draw_wallpaper() {
     clear
     echo -e "\e[44m\e[37m"
-    echo "                                                     "
-    echo "                                                     "
-    echo "                                                     "
-    echo "                                                     "
-    echo " ____      ____  ____    ____      _____  _________  "
-    echo "|_  _|    |_  _||_   \  /   _|    |_   _||  _   _  | "
-    echo "  \ \  /\  / /    |   \/   | ______ | |  |_/ | | \_| "
-    echo "   \ \/  \/ /     | |\  /| ||______|| |      | |     "
-    echo "    \  /\  /     _| |_\/_| |_      _| |_    _| |_    "
-    echo "     \/  \/     |_____||_____|    |_____|  |_____|   "
-    echo "                                                     "
-    echo "                                                     "
-    echo "                                                     "
-    echo "                                                     "
+    echo "                                                                             "
+    echo "                                                                             "
+    echo "  _    _   _____   __  Welcome to WM-IT!                                     "
+    echo " | |  | | |_   _| |  | WM-IT the best!                                       "
+    echo " | |__| |   | |   |  | WM-IT github:                                         "
+    echo " |  __  |   | |   |__| https://github.com/Pumba/WM-IT                        "
+    echo " | |  | |  _| |_   __  Creater: CowerDawn,MrPumba                            "
+    echo " |_|  |_| |_____| |__| WM-IT - This is a Windows manager inside the terminal!"
+    echo "                                                                             "
+    echo "                                                                             "
     echo -e "\e[0m"      
 }
 
@@ -207,6 +203,7 @@ function show_help() {
     echo "c - clear the screen"
     echo "y - clear the system"
     echo "help: Show this help"
+    echo "x: Update WM-IT"
 }
 
 function open_command_line() {
@@ -492,6 +489,18 @@ function check_distribution_support() {
     fi
 }
 
+function update_script() {
+    echo "Updating WM-IT..."
+    curl -o /tmp/WM-IT.sh https://raw.githubusercontent.com/CowerDawn/WM-IT/main/WM-IT.sh
+    if [ $? -eq 0 ]; then
+        sudo mv /tmp/WM-IT.sh "$(realpath "$0")"
+        sudo chmod +x "$(realpath "$0")"
+        echo "WM-IT has been updated. Please restart the script."
+        exit 0
+    else
+        echo "Failed to download the update. Please try again later."
+    fi
+}
 
 draw_wallpaper
 draw_menu
@@ -572,6 +581,9 @@ while true; do
     "y")
 	    clear_system
 	    ;;
+    "x")
+        update_script
+        ;;
     esac
     draw_menu
 done
